### ISSUE TITLE
Unit of roll/pitch/yaw

### ISSUE THREAD

**Issue by ca-schue** [chvmp/pychamp#1]
A question about the following lines:
https://github.com/chvmp/pychamp/blob/a15bc5cd818c699d3adb6cd38e0f8212203c7439/examples/sim.py#L103-L105

What exactly is passed to roll/pitch/yaw by `sine()`? An angle in radians or maybe an angular velocity? For example: what do I have to pass to `req_pose.orientation.pitch` to make the robot tilt 15° backwards?

**Comment by ca-schue** [comment]
I have already figured it out. You need an interpolation function over time. Actually quite logical

**Comment by grassjelly** [comment]
Hey, the unit's in radians and you can use it to set the robot's absolute pose reference to the imu frame
